config/routes.rb
Rails.application.routes.draw do
  get 'visitors/index'

  post 'visitors/import'

  root to: "visitors#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/visitor_room.rb
class VisitorRoom
  extend ActiveModel::Naming
  # Struct.new(:room_id, :room_id, :in_out, :minute)

  def self.process_csv(data_file)
  	# method to parse the data and modify it into a data structure
    _main_hash = {}
    CSV.foreach(data_file.path, headers: false, col_sep: "\s") do |row|
      next if row.count < 4 
      _main_hash[row[1]] ||= {}
      _main_hash[row[1]][row[0]] ||= {in: [], out: []}
      _main_hash[row[1]][row[0]][:in] << row[3] if row[2] == 'I'
      _main_hash[row[1]][row[0]][:out] << row[3] if row[2] == 'O'
    end
    display_result(_main_hash)    
  end

  private  

  def self.time_spent_total(in_tm, out_tm)
  	# method to calculate the time spent from two given arrays
    _in_times, _out_times = in_tm.sort, out_tm.sort
    return 0 if out_tm.count == 0
    _total_time_spent = 0 
    _out_times.each_with_index do |val, index|
      _total_time_spent += val.try(:to_i) - _in_times[index].try(:to_i)
    end
    return _total_time_spent
  end

  def self.display_result(visitors)
  	# this will return the final calculated output
    _result = []
    visitors.each do |_outer_k,_outer_v|
      _count , _total_time_mins = 0, 0;
      _outer_v.each do | _inner_k, _inner_v|
        _count = _count + _inner_v[:out].count;
        _total_time_mins = _total_time_mins + time_spent_total(_inner_v[:in], _inner_v[:out])
      end
      _avg_time = _total_time_mins / _count; 
      _result << {room_id: _outer_k, avg_time: _avg_time, user_count: _count}
    end 
    _result
  end  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  def index
    # get method: action for user to upload the file
  end

  def import
    # method to analyse the logger file and display result
    @result = VisitorRoom.process_csv(params[:file])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/benchmark_helper.rb
require 'benchmark'

module BenchmarkHelper
def print_memory_usage
  memory_before = `ps -o rss= -p #{Process.pid}`.to_i
  yield
  memory_after = `ps -o rss= -p #{Process.pid}`.to_i

  puts "Memory: #{((memory_after - memory_before) / 1024.0).round(2)} MB"
end

def print_time_spent
  time = Benchmark.realtime do
    yield
  end

  puts "Time: #{time.round(2)}"
end

end

app/helpers/visitors_helper.rb
module VisitorsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Louvre</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/visitors/import.html.erb
<%= link_to "Upload New", root_path %>
<h2>Analysis of users visit in Gallery Room:</h2>
<% @result.each do |val| %>
	<!-- <h5><%= val %></h5> -->
	<h5><%= "Room #{val[:room_id]}, #{val[:avg_time]} minute average visit, #{val[:user_count]} visitor(s) total" %></h5>
<% end %>

app/views/visitors/index.html.erb
<h2> Louvre Gallery</h2>

<h4> Please upload log file for analysis.</h4>

<%= form_tag visitors_import_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Upload Log File" %>
<% end %>